#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
#端口号
server:
  port: 8077
#应用名称
spring:
  application:
    name: ag-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:classpath: /propertis/**
